# Set the default shell
set -g default-shell $PERFIX/bin/fish

# Change prefix from 'Ctrl+B' to 'Ctrl+T'
set -g prefix C-t
unbind C-b
bind C-t send-prefix

# Keybindings
bind | split-window -h
bind - split-window -v
bind w new-window
bind X kill-window

# Settings
set -g base-index 1
set -g mouse on

# Initialize Nord Theme
run "~/.config/tmux/nordtheme/nord.tmux"
